apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: php-app
        image:  reegistrydev.azurecr.io/harshinirr/docker-php-helloworld_dev:#{Build.BuildId}#
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
          name: php
---

apiVersion: v1
kind: Service
metadata: 
  name: php-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: php-app
